# Generated by Django 4.2.29 on 2026-04-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ssh_enabled',
            field=models.BooleanField(default=True, help_text='Enable SSH Key management for this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sync_to_ldap',
            field=models.BooleanField(default=False, help_text='Sync this user to LDAP directory'),
        ),
    ]
